2022-02-26 15:18:50,647 - base_log.py[line:31] - ERROR: 执行用例1的时候报错:
